"use strict";

function escapeBudgetHtml(value = "") { const node = document.createElement("div"); node.textContent = value; return node.innerHTML; }

function budgetUsage(item, totals) { return totals.byCat[item.category] || 0; }

function budgetStatus(percent) { if (percent >= 100) return ["Exceeded", "exceeded"]; if (percent >= 80) return ["Warning", "warning"]; return ["Safe", "safe"]; }

function renderBudgetSummary(budgets, totals) { const totalBudget = budgets.reduce((sum, item) => sum + (Number(item.limit) || 0), 0); const totalSpent = budgets.reduce((sum, item) => sum + budgetUsage(item, totals), 0); const remaining = Math.max(0, totalBudget - totalSpent); const utilization = totalBudget ? Math.round(totalSpent / totalBudget * 100) : 0; const cards = [["Total Budget", fmt(totalBudget), "wallet", "#2563eb", "Your planned category limits"], ["Total Spent", fmt(totalSpent), "chart-line", "#ef4444", "Expenses recorded this month"], ["Remaining Budget", fmt(remaining), "piggy-bank", "#16a34a", "Available across your budgets"], ["Budget Utilization", `${utilization}%`, "gauge-high", "#f59e0b", "Of your total budget used"]]; document.getElementById("budgetSummary").innerHTML = cards.map(([label, value, icon, color, subtitle]) => `<article class="budget-card"><p><i class="fa-solid fa-${icon}" style="color:${color}"></i>${label}</p><h2>${value}</h2><span>${subtitle}</span></article>`).join(""); return { totalBudget, totalSpent, remaining, utilization }; }

function renderBudgetOverview(summary) { const percent = Math.min(100, summary.utilization); const color = summary.utilization >= 100 ? "#ef4444" : summary.utilization >= 80 ? "#f59e0b" : "#2563eb"; document.getElementById("budgetOverview").innerHTML = `<div class="budget-section-heading"><div><h2>Budget Overview</h2><p>Your overall spending position this month.</p></div><i class="fa-solid fa-chart-pie" style="color:${color}"></i></div><div class="overview-content"><div class="overview-ring" style="--overview-percent:${percent};--overview-color:${color}"><strong>${summary.utilization}%</strong></div><div class="overview-values"><div><span>Total Budget</span><strong>${fmt(summary.totalBudget)}</strong></div><div><span>Total Spending</span><strong>${fmt(summary.totalSpent)}</strong></div><div><span>Remaining Budget</span><strong>${fmt(summary.remaining)}</strong></div></div></div>`; }

function renderBudgetPage() { const budgets = load(K.budgets, []); const totals = monthTotals(thisMonth()); const summary = renderBudgetSummary(budgets, totals); renderBudgetOverview(summary); document.getElementById("budgetList").innerHTML = budgets.length ? budgets.map((item) => { const limit = Number(item.limit) || 0; const used = budgetUsage(item, totals); const remaining = Math.max(0, limit - used); const percent = limit ? Math.round(used / limit * 100) : 0; const [status, statusClass] = budgetStatus(percent); const category = catById(item.category); return `<article class="budget-item ${statusClass}"><div class="budget-item-head"><div class="budget-category"><span class="budget-category-icon" style="--category-color:${category.color}"><i class="fa-solid fa-${category.icon}"></i></span><div><h3>${category.name}</h3><p>${item.month ? new Date(`${item.month}-01T00:00:00`).toLocaleDateString(undefined, { month: "long", year: "numeric" }) : "Monthly budget"}</p></div></div><span class="budget-status ${statusClass}">${status}</span></div><div class="budget-progress-meta"><strong>Budget Usage</strong><span>${percent}% Used</span></div><div class="budget-progress"><span style="width:${Math.min(100, percent)}%"></span></div><div class="budget-values"><div><span>Budget Limit</span><strong>${fmt(limit)}</strong></div><div><span>Amount Spent</span><strong>${fmt(used)}</strong></div><div><span>Remaining</span><strong>${fmt(remaining)}</strong></div></div>${item.notes ? `<p class="budget-note"><i class="fa-regular fa-note-sticky"></i> ${escapeBudgetHtml(item.notes)}</p>` : ""}<div class="budget-actions"><button type="button" class="edit-budget" data-budget-action="edit" data-budget-category="${item.category}"><i class="fa-solid fa-pen"></i> Edit</button><button type="button" class="delete-budget" data-budget-action="delete" data-budget-category="${item.category}"><i class="fa-solid fa-trash"></i> Delete</button></div></article>`; }).join("") : `<section class="budget-empty"><div class="budget-empty-icon"><i class="fa-solid fa-wallet"></i></div><h2>No Budgets Created Yet</h2><p>Create a category limit to start managing your monthly spending.</p><button type="button" class="primary-btn" data-budget-action="add"><i class="fa-solid fa-plus"></i>Add Budget</button></section>`; }

function openBudgetModal(budget = null) { const form = document.getElementById("budgetForm"); form.reset(); document.getElementById("editingBudgetCategory").value = budget?.category || ""; document.getElementById("budgetModalTitle").textContent = budget ? "Edit Budget" : "Add Budget"; document.getElementById("budgetCategory").value = budget?.category || document.getElementById("budgetCategory").value; document.getElementById("budgetLimit").value = budget?.limit || ""; document.getElementById("budgetMonth").value = budget?.month || ""; document.getElementById("budgetNotes").value = budget?.notes || ""; document.getElementById("budgetModal").classList.remove("hidden"); document.getElementById("budgetLimit").focus(); }

function closeBudgetModal() { document.getElementById("budgetModal").classList.add("hidden"); }

function saveBudget(event) { event.preventDefault(); const oldCategory = document.getElementById("editingBudgetCategory").value; const budget = { category: document.getElementById("budgetCategory").value, limit: Number(document.getElementById("budgetLimit").value), month: document.getElementById("budgetMonth").value, notes: document.getElementById("budgetNotes").value.trim() }; const budgets = load(K.budgets, []).filter((item) => item.category !== oldCategory && item.category !== budget.category); budgets.push(budget); save(K.budgets, budgets); closeBudgetModal(); renderBudgetPage(); }

function initBudgetPage() { const category = document.getElementById("budgetCategory"); category.innerHTML = CATEGORIES.filter((item) => !["salary", "freelance"].includes(item.id)).map((item) => `<option value="${item.id}">${item.name}</option>`).join(""); const applyTheme = () => { const dark = localStorage.getItem("theme") === "dark"; document.body.classList.toggle("dark", dark); document.getElementById("themeIcon").className = `fa-solid fa-${dark ? "sun" : "moon"}`; }; applyTheme(); document.getElementById("themeToggle").onclick = () => { localStorage.setItem("theme", document.body.classList.contains("dark") ? "light" : "dark"); applyTheme(); }; document.getElementById("openBudgetModal").onclick = () => openBudgetModal(); document.getElementById("closeBudgetModal").onclick = closeBudgetModal; document.getElementById("cancelBudgetModal").onclick = closeBudgetModal; document.getElementById("budgetForm").onsubmit = saveBudget; document.getElementById("budgetList").onclick = (event) => { const button = event.target.closest("[data-budget-action]"); if (!button) return; const action = button.dataset.budgetAction; const categoryId = button.dataset.budgetCategory; if (action === "add") openBudgetModal(); if (action === "edit") openBudgetModal(load(K.budgets, []).find((item) => item.category === categoryId)); if (action === "delete") { save(K.budgets, load(K.budgets, []).filter((item) => item.category !== categoryId)); renderBudgetPage(); } }; document.getElementById("budgetModal").onclick = (event) => { if (event.target.id === "budgetModal") closeBudgetModal(); }; renderBudgetPage(); }

document.addEventListener("DOMContentLoaded", initBudgetPage);
