"use strict";

function escapeGoalHtml(value = "") { const node = document.createElement("div"); node.textContent = value; return node.innerHTML; }

function goalProgress(goal) { const target = Number(goal.target) || 0; return target ? Math.min(100, Math.round((Number(goal.saved) || 0) / target * 100)) : 0; }

function goalStatus(goal, percent) { if (percent >= 100) return ["Completed", "completed"]; if (goal.deadline) { const days = Math.ceil((new Date(`${goal.deadline}T00:00:00`) - new Date().setHours(0, 0, 0, 0)) / 86400000); if (days >= 0 && days <= 14) return ["Near Deadline", "near-deadline"]; } return ["In Progress", "in-progress"]; }

function renderGoalsSummary(goals) { const totalSaved = goals.reduce((sum, goal) => sum + (Number(goal.saved) || 0), 0); const totalTarget = goals.reduce((sum, goal) => sum + (Number(goal.target) || 0), 0); const completed = goals.filter((goal) => goalProgress(goal) >= 100).length; const cards = [["Total Goals", goals.length, "bullseye", "#7c3aed"], ["Total Saved", fmt(totalSaved), "piggy-bank", "#16a34a"], ["Remaining Amount", fmt(Math.max(0, totalTarget - totalSaved)), "wallet", "#2563eb"], ["Completed Goals", completed, "circle-check", "#f59e0b"]]; document.getElementById("goalsSummary").innerHTML = cards.map(([label, value, icon, color]) => `<article class="goal-summary-card"><p><i class="fa-solid fa-${icon}" style="color:${color}"></i> ${label}</p><h2>${value}</h2></article>`).join(""); }

function renderGoals() { const goals = getUserFinanceData(K.goals, []); renderGoalsSummary(goals); document.getElementById("goalsList").innerHTML = goals.length ? goals.map((goal, index) => { const saved = Number(goal.saved) || 0; const target = Number(goal.target) || 0; const remaining = Math.max(0, target - saved); const percent = goalProgress(goal); const [status, statusClass] = goalStatus(goal, percent); const deadline = goal.deadline ? fmtDate(goal.deadline) : "No deadline"; const icon = goal.icon || "bullseye"; return `<article class="goal-card"><div class="goal-card-head"><div class="goal-title-wrap"><span class="goal-icon"><i class="fa-solid fa-${escapeGoalHtml(icon)}"></i></span><div><h2>${escapeGoalHtml(goal.title)}</h2><p>Target ${fmt(target)}</p></div></div><span class="goal-status ${statusClass}">${status}</span></div><div class="goal-progress-meta"><strong>Progress</strong><span>${percent}% Complete</span></div><div class="goal-progress"><span style="width:${percent}%"></span></div><div class="goal-values"><div><span>Saved Amount</span><strong>${fmt(saved)}</strong></div><div><span>Remaining</span><strong>${fmt(remaining)}</strong></div></div><div class="goal-details"><span><i class="fa-regular fa-calendar"></i> Deadline</span><strong>${deadline}</strong></div><div class="goal-actions"><button type="button" class="edit-goal" data-goal-action="edit" data-goal-index="${index}"><i class="fa-solid fa-pen"></i> Edit</button><button type="button" class="delete-goal" data-goal-action="delete" data-goal-index="${index}"><i class="fa-solid fa-trash"></i> Delete</button></div></article>`; }).join("") : `<section class="goals-empty"><div class="goals-empty-icon"><i class="fa-solid fa-bullseye"></i></div><h2>No Goals Yet</h2><p>Create a goal to start planning your next financial milestone.</p><button type="button" class="primary-btn" data-goal-action="add"><i class="fa-solid fa-plus"></i>Create Your First Goal</button></section>`; }

function openGoalModal(goal = null, index = "") { const form = document.getElementById("goalForm"); form.reset(); document.getElementById("editingGoalIndex").value = index; document.getElementById("goalModalTitle").textContent = goal ? "Edit Goal" : "Add Goal"; document.getElementById("goalTitle").value = goal?.title || ""; document.getElementById("goalTarget").value = goal?.target || ""; document.getElementById("goalSaved").value = goal?.saved || 0; document.getElementById("goalDeadline").value = goal?.deadline || ""; document.getElementById("goalIcon").value = goal?.icon || "bullseye"; document.getElementById("goalModal").classList.remove("hidden"); document.getElementById("goalTitle").focus(); }

function closeGoalModal() { document.getElementById("goalModal").classList.add("hidden"); }

function saveGoal(event) { event.preventDefault(); const goals = getUserFinanceData(K.goals, []); const index = document.getElementById("editingGoalIndex").value; const goal = { title: document.getElementById("goalTitle").value.trim(), target: Number(document.getElementById("goalTarget").value), saved: Number(document.getElementById("goalSaved").value), deadline: document.getElementById("goalDeadline").value, icon: document.getElementById("goalIcon").value }; if (index === "") goals.push(goal); else goals[Number(index)] = goal; saveUserFinanceData(K.goals, goals); closeGoalModal(); renderGoals(); }

function initGoalsTheme() { const apply = () => { const dark = localStorage.getItem("theme") === "dark"; document.body.classList.toggle("dark", dark); document.getElementById("themeIcon").className = `fa-solid fa-${dark ? "sun" : "moon"}`; }; apply(); document.getElementById("themeToggle").onclick = () => { localStorage.setItem("theme", document.body.classList.contains("dark") ? "light" : "dark"); apply(); }; }

document.addEventListener("DOMContentLoaded", () => { initGoalsTheme(); document.getElementById("openGoalModal").onclick = () => openGoalModal(); document.getElementById("closeGoalModal").onclick = closeGoalModal; document.getElementById("cancelGoalModal").onclick = closeGoalModal; document.getElementById("goalForm").onsubmit = saveGoal; document.getElementById("goalsList").onclick = (event) => { const button = event.target.closest("[data-goal-action]"); if (!button) return; const action = button.dataset.goalAction; const index = button.dataset.goalIndex; if (action === "add") openGoalModal(); if (action === "edit") openGoalModal(getUserFinanceData(K.goals, [])[Number(index)], index); if (action === "delete") { const goals = getUserFinanceData(K.goals, []); goals.splice(Number(index), 1); saveUserFinanceData(K.goals, goals); renderGoals(); } }; document.getElementById("goalModal").onclick = (event) => { if (event.target.id === "goalModal") closeGoalModal(); }; renderGoals(); });
